-- adaptive persistence tables for neuro-adaptive state and event tracking
CREATE TABLE public.adaptive_profiles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, preferred_mode TEXT NOT NULL DEFAULT 'Concept Builder', cognitive_load NUMERIC NOT NULL DEFAULT 0.45, attention_stability NUMERIC NOT NULL DEFAULT 0.7, retrieval_strength NUMERIC NOT NULL DEFAULT 0.4, forgetting_probability NUMERIC NOT NULL DEFAULT 0.4, confidence_score NUMERIC NOT NULL DEFAULT 0.4, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.adaptive_profiles TO authenticated; GRANT ALL ON public.adaptive_profiles TO service_role; ALTER TABLE public.adaptive_profiles ENABLE ROW LEVEL SECURITY; CREATE POLICY "own adaptive profiles" ON public.adaptive_profiles FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE TABLE public.learning_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, event_type TEXT NOT NULL, topic TEXT, difficulty TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.learning_events TO authenticated; GRANT ALL ON public.learning_events TO service_role; ALTER TABLE public.learning_events ENABLE ROW LEVEL SECURITY; CREATE POLICY "own learning events" ON public.learning_events FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id); CREATE INDEX learning_events_user_created_idx ON public.learning_events(user_id, created_at DESC);
CREATE TABLE public.feedback_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, feedback_type TEXT NOT NULL, feedback_text TEXT NOT NULL, impact_score NUMERIC NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback_history TO authenticated; GRANT ALL ON public.feedback_history TO service_role; ALTER TABLE public.feedback_history ENABLE ROW LEVEL SECURITY; CREATE POLICY "own feedback history" ON public.feedback_history FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id); CREATE INDEX feedback_history_user_created_idx ON public.feedback_history(user_id, created_at DESC);
CREATE TABLE public.pattern_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, pattern_type TEXT NOT NULL, pattern_data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pattern_history TO authenticated; GRANT ALL ON public.pattern_history TO service_role; ALTER TABLE public.pattern_history ENABLE ROW LEVEL SECURITY; CREATE POLICY "own pattern history" ON public.pattern_history FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id); CREATE INDEX pattern_history_user_created_idx ON public.pattern_history(user_id, created_at DESC);
CREATE TABLE public.feature_vectors (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, feature_name TEXT NOT NULL, feature_value TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feature_vectors TO authenticated; GRANT ALL ON public.feature_vectors TO service_role; ALTER TABLE public.feature_vectors ENABLE ROW LEVEL SECURITY; CREATE POLICY "own feature vectors" ON public.feature_vectors FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id); CREATE INDEX feature_vectors_user_created_idx ON public.feature_vectors(user_id, created_at DESC);
CREATE TRIGGER adaptive_profiles_touch BEFORE UPDATE ON public.adaptive_profiles FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN INSERT INTO public.profiles (id, name, avatar_url) VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', split_part(NEW.email,'@',1)), NEW.raw_user_meta_data->>'avatar_url') ON CONFLICT (id) DO NOTHING; INSERT INTO public.learning_profiles (user_id) VALUES (NEW.id) ON CONFLICT (user_id) DO NOTHING; INSERT INTO public.adaptive_profiles (user_id) VALUES (NEW.id) ON CONFLICT (user_id) DO NOTHING; RETURN NEW; END; $$;
