ALTER TABLE public.learning_profiles
  ADD COLUMN IF NOT EXISTS topics JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS questions_answered INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS streak_days INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS improvement_score NUMERIC NOT NULL DEFAULT 0;
